apiVersion: v1
kind: ConfigMap
metadata:
    name: aws-creds
data:
    credentials: |
        [default]
        aws_access_key_id = AKIAUQJIGFXJP6BJIAFN
        aws_secret_access_key = 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
